name: da3em
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.7+7
environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.6
  provider: ^6.0.3
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  http: ^1.1.1
  shared_preferences: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  webview_flutter: ^4.4.4
  flutter_html: ^3.0.0-alpha.3
  share_plus: ^7.2.1
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.9
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  geocoding: ^2.0.0
  flutter_typeahead: ^4.0.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.14.11


  firebase_messaging: ^14.7.10
  flutter_local_notifications:
  firebase_core: ^2.15.1
  # google_maps_flutter: ^2.5.2
  flutter_facebook_auth:
  # geolocator: ^13.0.1
  permission_handler: ^11.1.0

  # flutter_downloader: ^1.11.6
  flutter_inappwebview: ^6.0.0

  path: ^1.8.3
  cached_network_image: ^3.4.1
  sign_in_with_apple: ^6.1.1

  just_audio: ^0.9.36
  file_picker: ^6.1.1

  dropdown_search: ^5.0.3
  http_parser: ^4.0.2
  fluttertoast: ^8.0.9
  intl: ^0.18.1
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  emoji_picker_flutter: ^1.6.2
  carousel_slider:
  webview_flutter_android: ^3.13.2
  webview_flutter_wkwebview: ^3.10.1
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.1
  iconsax: ^0.0.8
  navigation_view: ^1.0.6
  iconly: ^1.0.1



dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.19.0
  
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/icon-forground.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

flutter_launcher_icons:
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/fg.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/launcher/fg.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/logo_full.webp

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
